version: '2'

services:

  zammad-elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zammad-init:
    command: ["zammad-init"]
    image: ${IMAGE_REPO}:${VERSION}
    links:
      - zammad-elasticsearch
    restart: on-failure
    env_file:
      - db.env
    volumes:
      - zammad-data:/opt/zammad

  zammad-memcached:
    command: ["zammad-memcached"]
    image: zammad/zammad-docker-compose:zammad-memcached
    restart: always

  zammad-nginx:
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    image: ${IMAGE_REPO}:${VERSION}
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: always
    volumes:
      - zammad-data:/opt/zammad
    expose:
      - "80"

  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
    image: ${IMAGE_REPO}:${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
    restart: always
    volumes:
      - zammad-data:/opt/zammad

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:${VERSION}
    links:
      - zammad-elasticsearch
      - zammad-memcached
    restart: always
    volumes:
      - zammad-data:/opt/zammad

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    image: ${IMAGE_REPO}:${VERSION}
    links:
      - zammad-memcached
    restart: always
    volumes:
      - zammad-data:/opt/zammad

volumes:
  elasticsearch-data:
    driver: local
  zammad-data:
    driver: local
